### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by flatsiedatsie** [mrampersad/ot#1]
Is this code open source? If so, under what license may it be used?

**Comment by mrampersad** [comment]
what license would you prefer?

**Comment by flatsiedatsie** [comment]
MIT would be great :-)

**Comment by flatsiedatsie** [comment]
Would that be possible? I'd like to use your code as a startingpoint for an minimal open source notepad. I'd like to be able to quickly sketch out some ideas with someone while videochatting, for example. It would allow me to avoid always relying on Google Docs. I don't know if it will work, but I'd love to give it a try as quick side project.

**Comment by mrampersad** [comment]
MIT license applied.

**Comment by flatsiedatsie** [comment]
Hurray! Thank you very much!
